[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.4.1" }
wally = { github = "UpliftGames/wally", version = "0.3.2" }
wally-package-types = { github = "JohnnyMorganz/wally-package-types", version = "1.3.1" }
run-in-roblox = { github = "franydev/run-in-roblox", version = "0.3.1" }