[tools]
darklua = { github = "seaofvoices/darklua", version = "0.12.1" }
rojo = { github = "rojo-rbx/rojo", version = "7.4.1" }
wally = { github = "UpliftGames/wally", version = "0.3.2" }
wally-package-types = { github = "JohnnyMorganz/wally-package-types", version = "1.3.1" }
run-in-roblox = { github = "franydev/run-in-roblox", version = "0.3.1" }
luau-lsp = { github = "JohnnyMorganz/luau-lsp", version = "1.31.0" }
stylua = { github = "JohnnyMorganz/StyLua", version = "0.20.0" }
selene = { github = "Kampfkarren/Selene", version = "0.27.1"}