title = "YetAnotherNet"
gitSourceBranch = "main"
classOrder = [
    "Net",
    "Route",
    "Bridge",
    "QueryResult",
    "SendRequest",
    "Loop",
]

[docusaurus]
tagline = "A Data-Driven Networking Library, inspired by Bevy_Renet & BridgeNet2, made for ECS."
favicon = "Favicon.svg"
url = "https://yetanotherclown.github.io"
baseUrl = "/YetAnotherNet"

[[navbar.items]]
href = "https://discord.gg/nKCV5fjEvH"
label = "Roblox OSS Community"
position = "right"

[footer]
style = "dark"
copyright = "Copyright © 2023 YetAnotherClown. Built with Moonwave and Docusaurus"

[[footer.links]]
title = "Links"

[[footer.links.items]]
label = "Roblox OSS Community"
href = "https://discord.gg/nKCV5fjEvH"

[[footer.links.items]]
label = "YetAnotherClown on Github"
href = "https://github.com/YetAnotherClown"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Data-Driven"
description = "Net promotes a Data-Driven structure as opposed to an Event-Driven one."

[[home.features]]
title = "Optimized Bandwidth"
description = "Net automatically structures your data to optimize bandwidth."

[[home.features]]
title = "Made for ECS"
description = "First-Class support for ECS Architectures, made for the Matter ECS."