[package]
name = "yetanotherclown/yetanothernet"
description = "A Data-Driven Networking Library, inspired by BridgeNet2 & Bevy_Renet, made for the Matter ECS."
version = "0.7.0"
license = "MIT"
authors = ["YetAnotherClown"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = ["lib", "lib/*", "default.project.json", "wally.toml", "wally.lock"]

[dev-dependencies]
Jest = "jsdotlua/jest@3.6.1-rc.2"
JestGlobals = "jsdotlua/jest-globals@3.6.1-rc.2"
Signal = "sleitnick/signal@2.0.1"