[package]
name = "yetanotherclown/yetanothernet"
description = "A Data-Driven Networking Library, inspired by BridgeNet2 & Bevy_Renet, made for the Matter ECS."
version = "0.9.0"
license = "MIT"
authors = ["YetAnotherClown"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

# publish-wally.sh will clone to /dist and run wally publish in that directory
exclude = ["tests", "tests/*", "lib/__*__", "lib/__*__/*", "package.json", "*.tgz", "*.zip"]
include = ["wally.lock"]

[dev-dependencies]
Jest = "jsdotlua/jest@3.6.1-rc.2"
JestGlobals = "jsdotlua/jest-globals@3.6.1-rc.2"
Signal = "sleitnick/signal@2.0.1"